# coding:utf-8
'''
**************************************************
@File   ：Ui_MainWindow
@IDE    ：PyCharm
@Author ：Tianze Zhang
@Desc   , UIWindow
@Date   ：2025/1/23 20:48
**************************************************
'''

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QGroupBox, QHBoxLayout,
    QLabel, QMainWindow, QMenuBar, QPushButton,
    QRadioButton, QSizePolicy, QStatusBar, QTextEdit,
    QToolBar, QVBoxLayout, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1007, 775)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.pushButton2 = QPushButton(self.centralwidget)
        self.pushButton2.setObjectName(u"pushButton2")
        self.pushButton2.setGeometry(QRect(170, 650, 111, 31))
        self.pushButton2.setMaximumSize(QSize(300, 16777215))
        self.pushButton2.setAutoDefault(False)
        self.pushButton1 = QPushButton(self.centralwidget)
        self.pushButton1.setObjectName(u"pushButton1")
        self.pushButton1.setGeometry(QRect(20, 650, 111, 31))
        self.pushButton1.setMaximumSize(QSize(300, 16777215))
        self.pushButton1.setAutoDefault(False)
        self.layoutWidget = QWidget(self.centralwidget)
        self.layoutWidget.setObjectName(u"layoutWidget")
        self.layoutWidget.setGeometry(QRect(20, 210, 961, 421))
        self.horizontalLayout = QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.source = QVBoxLayout()
        self.source.setObjectName(u"source")

        self.horizontalLayout.addLayout(self.source)

        self.target = QVBoxLayout()
        self.target.setObjectName(u"target")

        self.horizontalLayout.addLayout(self.target)

        self.layoutWidget_2 = QWidget(self.centralwidget)
        self.layoutWidget_2.setObjectName(u"layoutWidget_2")
        self.layoutWidget_2.setGeometry(QRect(10, 0, 971, 71))
        self.horizontalLayout_2 = QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.groupBox = QGroupBox(self.layoutWidget_2)
        self.groupBox.setObjectName(u"groupBox")
        self.layoutWidget_3 = QWidget(self.groupBox)
        self.layoutWidget_3.setObjectName(u"layoutWidget_3")
        self.layoutWidget_3.setGeometry(QRect(10, 0, 361, 61))
        self.horizontalLayout_3 = QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.pushButton3 = QPushButton(self.layoutWidget_3)
        self.pushButton3.setObjectName(u"pushButton3")

        self.horizontalLayout_3.addWidget(self.pushButton3)

        self.textEdit1 = QTextEdit(self.layoutWidget_3)
        self.textEdit1.setObjectName(u"textEdit1")

        self.horizontalLayout_3.addWidget(self.textEdit1)

        self.pushButton12 = QPushButton(self.groupBox)
        self.pushButton12.setObjectName(u"pushButton12")
        self.pushButton12.setGeometry(QRect(380, 20, 91, 30))

        self.horizontalLayout_2.addWidget(self.groupBox)

        self.groupBox_2 = QGroupBox(self.layoutWidget_2)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.layoutWidget_4 = QWidget(self.groupBox_2)
        self.layoutWidget_4.setObjectName(u"layoutWidget_4")
        self.layoutWidget_4.setGeometry(QRect(10, 0, 361, 61))
        self.horizontalLayout_4 = QHBoxLayout(self.layoutWidget_4)
        self.horizontalLayout_4.setObjectName(u"horizontalLayout_4")
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.pushButton4 = QPushButton(self.layoutWidget_4)
        self.pushButton4.setObjectName(u"pushButton4")

        self.horizontalLayout_4.addWidget(self.pushButton4)

        self.textEdit2 = QTextEdit(self.layoutWidget_4)
        self.textEdit2.setObjectName(u"textEdit2")

        self.horizontalLayout_4.addWidget(self.textEdit2)

        self.pushButton13 = QPushButton(self.groupBox_2)
        self.pushButton13.setObjectName(u"pushButton13")
        self.pushButton13.setGeometry(QRect(370, 20, 91, 30))

        self.horizontalLayout_2.addWidget(self.groupBox_2)

        self.groupBox_3 = QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(20, 70, 471, 131))
        self.textEdit3 = QTextEdit(self.groupBox_3)
        self.textEdit3.setObjectName(u"textEdit3")
        self.textEdit3.setGeometry(QRect(240, 17, 91, 26))
        self.textEdit4 = QTextEdit(self.groupBox_3)
        self.textEdit4.setObjectName(u"textEdit4")
        self.textEdit4.setGeometry(QRect(240, 54, 111, 26))
        self.textEdit5 = QTextEdit(self.groupBox_3)
        self.textEdit5.setObjectName(u"textEdit5")
        self.textEdit5.setGeometry(QRect(240, 92, 91, 26))
        self.textEdit5.setLineWrapMode(QTextEdit.WidgetWidth)
        self.pushButton5 = QPushButton(self.groupBox_3)
        self.pushButton5.setObjectName(u"pushButton5")
        self.pushButton5.setGeometry(QRect(430, 53, 31, 65))
        self.radioButton1 = QRadioButton(self.groupBox_3)
        self.radioButton1.setObjectName(u"radioButton1")
        self.radioButton1.setGeometry(QRect(20, 20, 131, 20))
        self.radioButton2 = QRadioButton(self.groupBox_3)
        self.radioButton2.setObjectName(u"radioButton2")
        self.radioButton2.setGeometry(QRect(20, 70, 131, 20))
        self.textEdit6 = QTextEdit(self.groupBox_3)
        self.textEdit6.setObjectName(u"textEdit6")
        self.textEdit6.setGeometry(QRect(340, 92, 81, 26))
        self.verticalLayoutWidget = QWidget(self.groupBox_3)
        self.verticalLayoutWidget.setObjectName(u"verticalLayoutWidget")
        self.verticalLayoutWidget.setGeometry(QRect(160, 90, 73, 31))
        self.verticalLayout = QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.radioButton3 = QRadioButton(self.verticalLayoutWidget)
        self.radioButton3.setObjectName(u"radioButton3")

        self.verticalLayout.addWidget(self.radioButton3)

        self.label = QLabel(self.groupBox_3)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 49, 81, 16))
        self.label_2 = QLabel(self.groupBox_3)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 100, 81, 16))
        self.label_5 = QLabel(self.groupBox_3)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(200, 21, 31, 16))
        self.label_6 = QLabel(self.groupBox_3)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(150, 60, 91, 20))
        self.textEdit9 = QTextEdit(self.groupBox_3)
        self.textEdit9.setObjectName(u"textEdit9")
        self.textEdit9.setGeometry(QRect(84, 48, 61, 20))
        self.textEdit10 = QTextEdit(self.groupBox_3)
        self.textEdit10.setObjectName(u"textEdit10")
        self.textEdit10.setGeometry(QRect(84, 99, 61, 20))
        self.pushButton11 = QPushButton(self.groupBox_3)
        self.pushButton11.setObjectName(u"pushButton11")
        self.pushButton11.setGeometry(QRect(340, 17, 111, 26))
        self.textEdit11 = QTextEdit(self.groupBox_3)
        self.textEdit11.setObjectName(u"textEdit11")
        self.textEdit11.setGeometry(QRect(360, 54, 61, 26))
        self.groupBox_4 = QGroupBox(self.centralwidget)
        self.groupBox_4.setObjectName(u"groupBox_4")
        self.groupBox_4.setGeometry(QRect(500, 70, 481, 131))
        self.radioButton4 = QRadioButton(self.groupBox_4)
        self.radioButton4.setObjectName(u"radioButton4")
        self.radioButton4.setGeometry(QRect(20, 34, 95, 20))
        self.radioButton5 = QRadioButton(self.groupBox_4)
        self.radioButton5.setObjectName(u"radioButton5")
        self.radioButton5.setGeometry(QRect(20, 60, 95, 20))
        self.label_3 = QLabel(self.groupBox_4)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(220, 50, 41, 16))
        self.label_4 = QLabel(self.groupBox_4)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(186, 105, 91, 16))
        self.textEdit7 = QTextEdit(self.groupBox_4)
        self.textEdit7.setObjectName(u"textEdit7")
        self.textEdit7.setGeometry(QRect(280, 10, 191, 81))
        self.textEdit8 = QTextEdit(self.groupBox_4)
        self.textEdit8.setObjectName(u"textEdit8")
        self.textEdit8.setGeometry(QRect(280, 100, 191, 26))
        self.textEdit8.setLineWrapMode(QTextEdit.WidgetWidth)
        self.pushButton7 = QPushButton(self.groupBox_4)
        self.pushButton7.setObjectName(u"pushButton7")
        self.pushButton7.setGeometry(QRect(23, 88, 51, 25))
        self.comboBox2 = QComboBox(self.groupBox_4)
        self.comboBox2.setObjectName(u"comboBox2")
        self.comboBox2.setGeometry(QRect(110, 34, 101, 21))
        self.pushButton10 = QPushButton(self.groupBox_4)
        self.pushButton10.setObjectName(u"pushButton10")
        self.pushButton10.setGeometry(QRect(88, 88, 91, 25))
        self.pushButton6 = QPushButton(self.centralwidget)
        self.pushButton6.setObjectName(u"pushButton6")
        self.pushButton6.setGeometry(QRect(320, 650, 161, 31))
        self.pushButton6.setMaximumSize(QSize(300, 16777215))
        self.pushButton6.setAutoDefault(False)
        self.pushButton8 = QPushButton(self.centralwidget)
        self.pushButton8.setObjectName(u"pushButton8")
        self.pushButton8.setGeometry(QRect(560, 650, 161, 31))
        self.pushButton8.setMaximumSize(QSize(300, 16777215))
        self.pushButton8.setAutoDefault(False)
        self.pushButton9 = QPushButton(self.centralwidget)
        self.pushButton9.setObjectName(u"pushButton9")
        self.pushButton9.setGeometry(QRect(790, 650, 161, 31))
        self.pushButton9.setMaximumSize(QSize(300, 16777215))
        self.pushButton9.setAutoDefault(False)
        self.label_13 = QLabel(self.centralwidget)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(330, 700, 341, 20))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1007, 22))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QToolBar(MainWindow)
        self.toolBar.setObjectName(u"toolBar")
        MainWindow.addToolBar(Qt.TopToolBarArea, self.toolBar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.pushButton2.setText(QCoreApplication.translate("MainWindow", u"Show Target", None))
        self.pushButton1.setText(QCoreApplication.translate("MainWindow", u"Show Source", None))
        self.groupBox.setTitle("")
        self.pushButton3.setText(QCoreApplication.translate("MainWindow", u"Select Source Pointcloud Path", None))
        self.pushButton12.setText(QCoreApplication.translate("MainWindow", u"Save", None))
        self.groupBox_2.setTitle("")
        self.pushButton4.setText(QCoreApplication.translate("MainWindow", u"Select Target Pointcloud Path", None))
        self.pushButton13.setText(QCoreApplication.translate("MainWindow", u"Save", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("MainWindow", u"Pointcloud Preprocessing", None))
        self.textEdit3.setPlaceholderText("")
        self.textEdit4.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Enter Target Num", None))
        self.textEdit5.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Neigbour", None))
        self.pushButton5.setText(QCoreApplication.translate("MainWindow", u"Do", None))
        self.radioButton1.setText(QCoreApplication.translate("MainWindow", u"Source Pointcloud", None))
        self.radioButton2.setText(QCoreApplication.translate("MainWindow", u"Target Pointcloud", None))
        self.textEdit6.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Thresold", None))
        self.radioButton3.setText(QCoreApplication.translate("MainWindow", u"Statistic", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Point Nums:", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Point Nums:", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Scale", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"DownSampling", None))
        self.pushButton11.setText(QCoreApplication.translate("MainWindow", u"Scale Transform", None))
        self.textEdit11.setPlaceholderText("")
        self.groupBox_4.setTitle(QCoreApplication.translate("MainWindow", u"Pointcloud Registration", None))
        self.radioButton4.setText(QCoreApplication.translate("MainWindow", u"Traditional", None))
        self.radioButton5.setText(QCoreApplication.translate("MainWindow", u"DNN", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Matrix", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Error\uff08MSE\uff09", None))
        self.textEdit7.setPlaceholderText("")
        self.textEdit8.setPlaceholderText("")
        self.pushButton7.setText(QCoreApplication.translate("MainWindow", u"Reg", None))
        self.pushButton10.setText(QCoreApplication.translate("MainWindow", u"Calculate", None))
        self.pushButton6.setText(QCoreApplication.translate("MainWindow", u"Show Preprocessing", None))
        self.pushButton8.setText(QCoreApplication.translate("MainWindow", u"Show Coarse Registration", None))
        self.pushButton9.setText(QCoreApplication.translate("MainWindow", u"Show Fine Registration", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"Aurthor: Tianze Zhang  Email: skyzhang0730@gmail.com", None))
        self.toolBar.setWindowTitle(QCoreApplication.translate("MainWindow", u"toolBar", None))
    # retranslateUi

