# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'HIT PCRegistration MasterwYsOPA.ui'
##
## Created by: Qt User Interface Compiler version 6.1.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import *  # type: ignore
from PySide6.QtGui import *  # type: ignore
from PySide6.QtWidgets import *  # type: ignore


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1025, 775)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.pushButton2 = QPushButton(self.centralwidget)
        self.pushButton2.setObjectName(u"pushButton2")
        self.pushButton2.setGeometry(QRect(170, 650, 111, 31))
        self.pushButton2.setMaximumSize(QSize(300, 16777215))
        self.pushButton2.setAutoDefault(False)
        self.pushButton1 = QPushButton(self.centralwidget)
        self.pushButton1.setObjectName(u"pushButton1")
        self.pushButton1.setGeometry(QRect(20, 650, 111, 31))
        self.pushButton1.setMaximumSize(QSize(300, 16777215))
        self.pushButton1.setAutoDefault(False)
        self.layoutWidget = QWidget(self.centralwidget)
        self.layoutWidget.setObjectName(u"layoutWidget")
        self.layoutWidget.setGeometry(QRect(20, 210, 961, 421))
        self.horizontalLayout = QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.source = QVBoxLayout()
        self.source.setObjectName(u"source")

        self.horizontalLayout.addLayout(self.source)

        self.target = QVBoxLayout()
        self.target.setObjectName(u"target")

        self.horizontalLayout.addLayout(self.target)

        self.layoutWidget_2 = QWidget(self.centralwidget)
        self.layoutWidget_2.setObjectName(u"layoutWidget_2")
        self.layoutWidget_2.setGeometry(QRect(10, 0, 971, 71))
        self.horizontalLayout_2 = QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.groupBox = QGroupBox(self.layoutWidget_2)
        self.groupBox.setObjectName(u"groupBox")
        self.layoutWidget_3 = QWidget(self.groupBox)
        self.layoutWidget_3.setObjectName(u"layoutWidget_3")
        self.layoutWidget_3.setGeometry(QRect(10, 30, 361, 31))
        self.horizontalLayout_3 = QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.pushButton3 = QPushButton(self.layoutWidget_3)
        self.pushButton3.setObjectName(u"pushButton3")

        self.horizontalLayout_3.addWidget(self.pushButton3)

        self.textEdit1 = QTextEdit(self.layoutWidget_3)
        self.textEdit1.setObjectName(u"textEdit1")

        self.horizontalLayout_3.addWidget(self.textEdit1)

        self.pushButton12 = QPushButton(self.groupBox)
        self.pushButton12.setObjectName(u"pushButton12")
        self.pushButton12.setGeometry(QRect(380, 31, 91, 30))

        self.horizontalLayout_2.addWidget(self.groupBox)

        self.groupBox_2 = QGroupBox(self.layoutWidget_2)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.layoutWidget_4 = QWidget(self.groupBox_2)
        self.layoutWidget_4.setObjectName(u"layoutWidget_4")
        self.layoutWidget_4.setGeometry(QRect(10, 30, 361, 31))
        self.horizontalLayout_4 = QHBoxLayout(self.layoutWidget_4)
        self.horizontalLayout_4.setObjectName(u"horizontalLayout_4")
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.pushButton4 = QPushButton(self.layoutWidget_4)
        self.pushButton4.setObjectName(u"pushButton4")

        self.horizontalLayout_4.addWidget(self.pushButton4)

        self.textEdit2 = QTextEdit(self.layoutWidget_4)
        self.textEdit2.setObjectName(u"textEdit2")

        self.horizontalLayout_4.addWidget(self.textEdit2)

        self.pushButton13 = QPushButton(self.groupBox_2)
        self.pushButton13.setObjectName(u"pushButton13")
        self.pushButton13.setGeometry(QRect(380, 30, 91, 30))

        self.horizontalLayout_2.addWidget(self.groupBox_2)

        self.groupBox_3 = QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(20, 70, 471, 131))
        self.textEdit3 = QTextEdit(self.groupBox_3)
        self.textEdit3.setObjectName(u"textEdit3")
        self.textEdit3.setGeometry(QRect(240, 17, 91, 26))
        self.textEdit4 = QTextEdit(self.groupBox_3)
        self.textEdit4.setObjectName(u"textEdit4")
        self.textEdit4.setGeometry(QRect(240, 54, 101, 26))
        self.textEdit5 = QTextEdit(self.groupBox_3)
        self.textEdit5.setObjectName(u"textEdit5")
        self.textEdit5.setGeometry(QRect(240, 92, 91, 26))
        self.textEdit5.setLineWrapMode(QTextEdit.WidgetWidth)
        self.pushButton5 = QPushButton(self.groupBox_3)
        self.pushButton5.setObjectName(u"pushButton5")
        self.pushButton5.setGeometry(QRect(430, 53, 31, 65))
        self.radioButton1 = QRadioButton(self.groupBox_3)
        self.radioButton1.setObjectName(u"radioButton1")
        self.radioButton1.setGeometry(QRect(56, 22, 61, 20))
        self.radioButton2 = QRadioButton(self.groupBox_3)
        self.radioButton2.setObjectName(u"radioButton2")
        self.radioButton2.setGeometry(QRect(51, 73, 71, 20))
        self.textEdit6 = QTextEdit(self.groupBox_3)
        self.textEdit6.setObjectName(u"textEdit6")
        self.textEdit6.setGeometry(QRect(340, 92, 81, 26))
        self.verticalLayoutWidget = QWidget(self.groupBox_3)
        self.verticalLayoutWidget.setObjectName(u"verticalLayoutWidget")
        self.verticalLayoutWidget.setGeometry(QRect(160, 90, 73, 31))
        self.verticalLayout = QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.radioButton3 = QRadioButton(self.verticalLayoutWidget)
        self.radioButton3.setObjectName(u"radioButton3")

        self.verticalLayout.addWidget(self.radioButton3)

        self.label = QLabel(self.groupBox_3)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 49, 81, 16))
        self.label_2 = QLabel(self.groupBox_3)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(5, 100, 81, 16))
        self.label_5 = QLabel(self.groupBox_3)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(178, 21, 51, 16))
        self.label_6 = QLabel(self.groupBox_3)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(183, 59, 41, 16))
        self.textEdit9 = QTextEdit(self.groupBox_3)
        self.textEdit9.setObjectName(u"textEdit9")
        self.textEdit9.setGeometry(QRect(84, 48, 72, 20))
        self.textEdit10 = QTextEdit(self.groupBox_3)
        self.textEdit10.setObjectName(u"textEdit10")
        self.textEdit10.setGeometry(QRect(84, 99, 72, 20))
        self.pushButton11 = QPushButton(self.groupBox_3)
        self.pushButton11.setObjectName(u"pushButton11")
        self.pushButton11.setGeometry(QRect(340, 17, 81, 26))
        self.textEdit11 = QTextEdit(self.groupBox_3)
        self.textEdit11.setObjectName(u"textEdit11")
        self.textEdit11.setGeometry(QRect(350, 54, 71, 26))
        self.groupBox_4 = QGroupBox(self.centralwidget)
        self.groupBox_4.setObjectName(u"groupBox_4")
        self.groupBox_4.setGeometry(QRect(500, 70, 481, 131))
        self.radioButton4 = QRadioButton(self.groupBox_4)
        self.radioButton4.setObjectName(u"radioButton4")
        self.radioButton4.setGeometry(QRect(20, 34, 95, 20))
        self.radioButton5 = QRadioButton(self.groupBox_4)
        self.radioButton5.setObjectName(u"radioButton5")
        self.radioButton5.setGeometry(QRect(20, 60, 95, 20))
        self.label_3 = QLabel(self.groupBox_4)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(206, 41, 51, 16))
        self.label_4 = QLabel(self.groupBox_4)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(186, 105, 91, 16))
        self.textEdit7 = QTextEdit(self.groupBox_4)
        self.textEdit7.setObjectName(u"textEdit7")
        self.textEdit7.setGeometry(QRect(280, 10, 191, 81))
        self.textEdit8 = QTextEdit(self.groupBox_4)
        self.textEdit8.setObjectName(u"textEdit8")
        self.textEdit8.setGeometry(QRect(280, 100, 191, 26))
        self.textEdit8.setLineWrapMode(QTextEdit.WidgetWidth)
        self.pushButton7 = QPushButton(self.groupBox_4)
        self.pushButton7.setObjectName(u"pushButton7")
        self.pushButton7.setGeometry(QRect(23, 88, 51, 25))
        self.comboBox2 = QComboBox(self.groupBox_4)
        self.comboBox2.setObjectName(u"comboBox2")
        self.comboBox2.setGeometry(QRect(97, 34, 81, 21))
        self.pushButton10 = QPushButton(self.groupBox_4)
        self.pushButton10.setObjectName(u"pushButton10")
        self.pushButton10.setGeometry(QRect(88, 88, 91, 25))
        self.pushButton6 = QPushButton(self.centralwidget)
        self.pushButton6.setObjectName(u"pushButton6")
        self.pushButton6.setGeometry(QRect(320, 650, 161, 31))
        self.pushButton6.setMaximumSize(QSize(300, 16777215))
        self.pushButton6.setAutoDefault(False)
        self.pushButton8 = QPushButton(self.centralwidget)
        self.pushButton8.setObjectName(u"pushButton8")
        self.pushButton8.setGeometry(QRect(520, 650, 131, 31))
        self.pushButton8.setMaximumSize(QSize(300, 16777215))
        self.pushButton8.setAutoDefault(False)
        self.pushButton9 = QPushButton(self.centralwidget)
        self.pushButton9.setObjectName(u"pushButton9")
        self.pushButton9.setGeometry(QRect(690, 650, 131, 31))
        self.pushButton9.setMaximumSize(QSize(300, 16777215))
        self.pushButton9.setAutoDefault(False)
        self.label_13 = QLabel(self.centralwidget)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(370, 700, 271, 20))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1025, 22))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QToolBar(MainWindow)
        self.toolBar.setObjectName(u"toolBar")
        MainWindow.addToolBar(Qt.TopToolBarArea, self.toolBar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.pushButton2.setText(QCoreApplication.translate("MainWindow", u"\u663e\u793a\u76ee\u6807\u70b9\u4e91", None))
        self.pushButton1.setText(QCoreApplication.translate("MainWindow", u"\u663e\u793a\u6e90\u70b9\u4e91", None))
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"\u6e90\u70b9\u4e91\u8def\u5f84", None))
        self.pushButton3.setText(QCoreApplication.translate("MainWindow", u"\u9009\u62e9\u6e90\u70b9\u4e91\u8def\u5f84", None))
        self.pushButton12.setText(QCoreApplication.translate("MainWindow", u"\u4fdd\u5b58\u6e90\u70b9\u4e91", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("MainWindow", u"\u76ee\u6807\u70b9\u4e91\u8def\u5f84", None))
        self.pushButton4.setText(QCoreApplication.translate("MainWindow", u"\u9009\u62e9\u76ee\u6807\u70b9\u4e91\u8def\u5f84", None))
        self.pushButton13.setText(QCoreApplication.translate("MainWindow", u"\u4fdd\u5b58\u76ee\u6807\u70b9\u4e91", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("MainWindow", u"\u70b9\u4e91\u9884\u5904\u7406", None))
        self.textEdit3.setPlaceholderText("")
        self.textEdit4.setPlaceholderText(QCoreApplication.translate("MainWindow", u"\u8bf7\u8f93\u5165\u76ee\u6807\u70b9\u6570", None))
        self.textEdit5.setPlaceholderText(QCoreApplication.translate("MainWindow", u"\u8bf7\u8f93\u5165\u90bb\u57df\u70b9", None))
        self.pushButton5.setText(QCoreApplication.translate("MainWindow", u"\u5904\u7406", None))
        self.radioButton1.setText(QCoreApplication.translate("MainWindow", u"\u6e90\u70b9\u4e91", None))
        self.radioButton2.setText(QCoreApplication.translate("MainWindow", u"\u76ee\u6807\u70b9\u4e91", None))
        self.textEdit6.setPlaceholderText(QCoreApplication.translate("MainWindow", u"\u8bf7\u8f93\u5165\u9608\u503c", None))
        self.radioButton3.setText(QCoreApplication.translate("MainWindow", u"\u7edf\u8ba1\u6ee4\u6ce2", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"\u6e90\u70b9\u4e91\u70b9\u6570\uff1a", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"\u76ee\u6807\u70b9\u4e91\u70b9\u6570\uff1a", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"\u5c3a\u5ea6\u53d8\u5316", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"\u964d\u91c7\u6837", None))
        self.pushButton11.setText(QCoreApplication.translate("MainWindow", u"\u5c3a\u5ea6\u53d8\u5316", None))
        self.textEdit11.setPlaceholderText("")
        self.groupBox_4.setTitle(QCoreApplication.translate("MainWindow", u"\u70b9\u4e91\u914d\u51c6", None))
        self.radioButton4.setText(QCoreApplication.translate("MainWindow", u"\u4f20\u7edf\u65b9\u6cd5", None))
        self.radioButton5.setText(QCoreApplication.translate("MainWindow", u"\u6df1\u5ea6\u914d\u51c6\u7f51\u7edc", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"\u8f6c\u6362\u77e9\u9635", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"\u914d\u51c6\u8bef\u5dee\uff08MSE\uff09", None))
        self.textEdit7.setPlaceholderText("")
        self.textEdit8.setPlaceholderText("")
        self.pushButton7.setText(QCoreApplication.translate("MainWindow", u"\u914d\u51c6", None))
        self.pushButton10.setText(QCoreApplication.translate("MainWindow", u"\u8ba1\u7b97\u914d\u51c6\u7ed3\u679c", None))
        self.pushButton6.setText(QCoreApplication.translate("MainWindow", u"\u663e\u793a\u9884\u5904\u7406\u540e\u4e24\u70b9\u4e91", None))
        self.pushButton8.setText(QCoreApplication.translate("MainWindow", u"\u663e\u793a\u7c97\u914d\u51c6\u540e\u4e24\u70b9\u4e91", None))
        self.pushButton9.setText(QCoreApplication.translate("MainWindow", u"\u663e\u793a\u7cbe\u914d\u51c6\u540e\u4e24\u70b9\u4e91", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"\u4f5c\u8005\uff1a\u5f20\u5929\u6cfd  \u54c8\u5c14\u6ee8\u5de5\u4e1a\u5927\u5b66  QQ:1604055758 ", None))
        self.toolBar.setWindowTitle(QCoreApplication.translate("MainWindow", u"toolBar", None))
    # retranslateUi

